security:
  jwt:
    token:
      secretKey: 53cr3753cr3753cr3753cr3753cr3753cr3753cr3753cr3753cr3753cr37
      tokenPrefix: "Bearer "
      validityInMilliseconds: 86400000
cors:
  originPatterns: http://localhost:8080,http://localhost:3000,https://github.com/gust4ngl
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bank?useTimezone=true&serverTimezone=UTC
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: false
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher
spring-doc:
  pathsToMatch: /api/**/v1/**
  swagger-ui:
    use-root-path: true